# Generated by Django 5.0 on 2023-12-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'booking',
            },
        ),
        migrations.AlterField(
            model_name='productesmodel',
            name='categories',
            field=models.ManyToManyField(related_name='product', to='pages.categorymodel'),
        ),
    ]
