# Generated by Django 5.0 on 2023-12-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_bookingmodel_alter_productesmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
